services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rentals_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_i9lWB3ATgHKw@ep-polished-glitter-agbmdnof-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
    depends_on:
      - db
    env_file:
      - .env

  qcluster:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_i9lWB3ATgHKw@ep-polished-glitter-agbmdnof-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
    depends_on:
      - db
volumes:
  postgres_data: