version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      # To poniżej sprawia, że baza danych zostaje na Twoim dysku:
      - sqlite_data:/app/db_data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  sqlite_data: