# Generated by Django 6.0.3 on 2026-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_addontype_branch_addon_daily_price_city_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
