# Generated by Django 5.2.12 on 2026-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0004_car_color_car_year_alter_addon_id_alter_addontype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
