# Generated by Django 5.2.12 on 2026-03-29 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0005_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
