# Generated by Django 5.2.13 on 2026-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_auto_20260408_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
