# Generated by Django 5.2.13 on 2026-04-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0008_car_milage'),
    ]

    operations = [
        migrations.RunSQL("""
                -- 1. FUNKCJE I TRIGGERY
                CREATE OR REPLACE FUNCTION znizka_lojalnosciowa(f_user_id INT)
                RETURNS INT AS $$
                DECLARE v_liczba_wypozyczen INT;
                BEGIN
                    SELECT COUNT(*) INTO v_liczba_wypozyczen FROM strona_rental WHERE user_id=f_user_id;
                    IF v_liczba_wypozyczen >= 20 THEN RETURN 20;
                    ELSIF v_liczba_wypozyczen >= 10 THEN RETURN 10;
                    ELSE RETURN 0; END IF;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION fn_sprawdz_numer_prawojazdy()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF (SELECT license_number FROM strona_userprofile WHERE user_id=NEW.user_id) IS NULL THEN 
                        RAISE EXCEPTION 'Musisz dodac numer prawo jazdy przed wypozyczeniem!';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION fn_zmien_przebieg()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF OLD.milage > NEW.milage THEN 
                        RAISE EXCEPTION 'Nie mozna cofnac przebiegu!';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION fn_zarzadzaj_dostepnoscia()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.status_id IN (1,2,3) THEN
                        UPDATE strona_car SET is_available = FALSE WHERE id = NEW.car_id;
                    ELSIF NEW.status_id IN (4,5) THEN
                        UPDATE strona_car SET is_available = TRUE WHERE id = NEW.car_id;
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION fn_sprawdz_daty()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.return_date < NEW.pickup_date THEN
                        RAISE EXCEPTION 'Data zwrotu nie moze byc wczesniejsza niz odbioru!';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;

                -- 2. PROCEDURY
                CREATE OR REPLACE PROCEDURE pr_serwis_aut(p_branch_id INT, p_item_id INT)
                AS $$
                BEGIN
                    INSERT INTO strona_maintenance(car_id, item_id, last_service_date, mileage_at_service)
                    SELECT id, p_item_id, CURRENT_DATE, mileage FROM strona_car WHERE current_branch_id = p_branch_id;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE PROCEDURE pr_zmien_ceny_w_oddziale(p_branch_id INT, p_procent DECIMAL)
                AS $$
                BEGIN
                    UPDATE strona_car SET price_per_day = price_per_day * (1 + p_procent / 100) WHERE current_branch_id = p_branch_id;
                END; $$ LANGUAGE plpgsql;

                CREATE OR REPLACE PROCEDURE zwolnij_dlugo_oczekujace_rezerwacje()
                AS $$
                BEGIN
                    UPDATE strona_rental SET status_id = 5 WHERE status_id = 1 AND created_at < NOW() - INTERVAL '5 minutes';
                END; $$ LANGUAGE plpgsql;

                -- 3. PODPIECIE TRIGGERÓW
                DROP TRIGGER IF EXISTS trg_prawko ON strona_rental;
                CREATE TRIGGER trg_prawko BEFORE INSERT ON strona_rental FOR EACH ROW EXECUTE FUNCTION fn_sprawdz_numer_prawojazdy();

                DROP TRIGGER IF EXISTS trg_przebieg ON strona_car;
                CREATE TRIGGER trg_przebieg BEFORE UPDATE ON strona_car FOR EACH ROW EXECUTE FUNCTION fn_zmien_przebieg();

                DROP TRIGGER IF EXISTS zmien_status ON strona_rental;
                CREATE TRIGGER zmien_status AFTER INSERT OR UPDATE ON strona_rental FOR EACH ROW EXECUTE FUNCTION fn_zarzadzaj_dostepnoscia();

                DROP TRIGGER IF EXISTS trg_poprawne_daty ON strona_rental;
                CREATE TRIGGER trg_poprawne_daty BEFORE INSERT OR UPDATE ON strona_rental FOR EACH ROW EXECUTE FUNCTION fn_sprawdz_daty();
            """)
    ]
