# Generated by Django 5.2.13 on 2026-04-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_auto_20260411_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='mileage',
        ),
    ]
