# Generated by Django 5.2.13 on 2026-04-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0010_rename_milage_car_mileage'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE PROCEDURE pr_serwis_aut(p_branch_id INTEGER, p_item_id INTEGER)
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    INSERT INTO strona_maintenance(car_id, item_id, last_service_date, mileage_at_service)
                    SELECT id, p_item_id, CURRENT_DATE, mileage
                    FROM strona_car 
                    WHERE current_branch_id = p_branch_id;
                END;
                $$;
                """,
            reverse_sql="DROP PROCEDURE IF EXISTS pr_serwis_aut(INTEGER, INTEGER);"
        ),
    ]
