# Generated by Django 5.2.13 on 2026-04-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0011_add_service_procedure'),
    ]

    operations = [
    ]
