# Generated by Django 5.2.13 on 2026-04-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0012_finalna_logika_sql'),
    ]

    operations = [
        migrations.RunSQL("""
        -- Sprawdzanie prawa jazdy

CREATE OR REPLACE FUNCTION fn_sprawdz_numer_prawojazdy()

RETURNS TRIGGER AS $$

BEGIN

IF(SELECT license_number

FROM strona_userprofile

WHERE id=NEW.user_id) IS NULL THEN 

RAISE EXCEPTION 'Musisz dodany numer swoich prawo jazdy przed wypożyczeniem auta';

END IF;

RETURN NEW;

END;

$$ LANGUAGE plpgsql;



CREATE OR REPLACE TRIGGER trg_prawko

BEFORE INSERT ON strona_rental

FOR EACH ROW

EXECUTE FUNCTION fn_sprawdz_numer_prawojazdy();



-- Blokada cofania licznika (Zmienione milage -> mileage)

CREATE OR REPLACE FUNCTION fn_zmien_przebieg()

RETURNS TRIGGER AS $$

BEGIN

IF OLD.mileage > NEW.mileage THEN 

RAISE EXCEPTION 'Nie można cofnąć przebiegu!!!!!';

END IF;

RETURN NEW;

END;

$$ LANGUAGE plpgsql;



CREATE OR REPLACE TRIGGER trg_przebieg

BEFORE UPDATE ON strona_car

FOR EACH ROW

EXECUTE FUNCTION fn_zmien_przebieg();



-- Zarządzanie dostępnością

CREATE OR REPLACE FUNCTION fn_zarzadzaj_dostepnoscia()

RETURNS TRIGGER AS $$

BEGIN

IF NEW.status_id IN (1,2,3) THEN

UPDATE strona_car 

SET is_available=FALSE

WHERE id=NEW.car_id;



ELSIF NEW.status_id IN (4,5) THEN

UPDATE strona_car

SET is_available=TRUE

WHERE id=NEW.car_id;

END IF;

RETURN NEW;

END;

$$ LANGUAGE plpgsql;



CREATE OR REPLACE TRIGGER zmien_status

AFTER INSERT OR UPDATE ON strona_rental

FOR EACH ROW

EXECUTE FUNCTION fn_zarzadzaj_dostepnoscia();



-- Sprawdzanie dat

CREATE OR REPLACE FUNCTION fn_sprawdz_daty()

RETURNS TRIGGER AS $$

BEGIN

IF NEW.return_date<NEW.pickup_date THEN

RAISE EXCEPTION 'Data zwrotu nie może być wcześniej niż taka odbioru!!';

END IF;

RETURN NEW;

END;

$$ LANGUAGE plpgsql;



CREATE OR REPLACE TRIGGER trg_poprawne_daty

BEFORE INSERT OR UPDATE ON strona_rental

FOR EACH ROW

EXECUTE FUNCTION fn_sprawdz_daty();



-- Obliczanie ceny

CREATE OR REPLACE FUNCTION oblicz_cene_wypozyczenia(

    f_id_car INT, 

    f_id_addon INT, 

    f_days INT,

    f_user_id INT

)

RETURNS DECIMAL AS $$

DECLARE

    v_cena_auta DECIMAL;

    v_cena_dodatku DECIMAL;

    v_wynik DECIMAL;

    v_wynik_po_rabacie DECIMAL;

    v_rabat INT;

BEGIN

    SELECT (price_per_day * f_days) INTO v_cena_auta

    FROM strona_car

    WHERE id = f_id_car;



    SELECT COALESCE(daily_price * f_days, 0) INTO v_cena_dodatku    

    FROM strona_addon

    WHERE id = f_id_addon;



    v_wynik := v_cena_auta + v_cena_dodatku;



    v_rabat := COALESCE(znizka_lojalnosciowa(f_user_id), 0);

    

    v_wynik_po_rabacie := v_wynik * ((100.0 - v_rabat) / 100.0);

    RETURN v_wynik_po_rabacie;

END;$$ LANGUAGE plpgsql;



-- Ilość aut w oddziale

CREATE OR REPLACE FUNCTION oblicz_ilosc_aut_w_oddziale(

    f_id_oddzialu INT

)

RETURNS INT AS $$

DECLARE

    wynik INT;

BEGIN

    SELECT COUNT(*) INTO wynik

    FROM strona_car C

    JOIN strona_branch B ON C.current_branch_id=B.id

    WHERE B.id=f_id_oddzialu;



    RETURN wynik;

END; $$LANGUAGE plpgsql;



-- Zniżka lojalnościowa

CREATE OR REPLACE FUNCTION znizka_lojalnosciowa(

    f_user_id INT)

RETURNS INT AS $$

DECLARE

    v_liczba_wypozyczen INT;

    v_rabat INT;

BEGIN

    SELECT COUNT(*) INTO v_liczba_wypozyczen 

    FROM strona_rental

    WHERE user_id=f_user_id;



    IF v_liczba_wypozyczen >= 20 THEN

        v_rabat := 20;

    ELSIF v_liczba_wypozyczen >= 10 THEN

        v_rabat := 10;

    ELSE

        v_rabat:= 0;

    END IF;

    RETURN v_rabat;

END; $$ LANGUAGE plpgsql;



-- Masowy serwis (Tu już miałeś mileage)

CREATE OR REPLACE PROCEDURE pr_serwis_aut(p_branch_id INT,p_item_id INT)

AS $$

BEGIN

INSERT INTO strona_maintenance(car_id, item_id, last_service_date, mileage_at_service)

SELECT id,p_item_id,CURRENT_DATE,mileage

FROM strona_car

WHERE current_branch_id=p_branch_id;



RAISE NOTICE 'Dodano serwis dla wszystkich aut w oddziale %', p_branch_id;

END;

$$ LANGUAGE plpgsql;



-- Zmiana cen

CREATE OR REPLACE PROCEDURE pr_zmien_ceny_w_oddziale(p_branch_id INT,p_procent DECIMAL)

AS $$

BEGIN

UPDATE strona_car

SET price_per_day=price_per_day*(1 + p_procent / 100)

WHERE current_branch_id=p_branch_id;



RAISE NOTICE 'Zaktualizowano ceny w oddziale % o % procent',p_branch_id,p_procent;

END;

$$ LANGUAGE plpgsql;



-- Zwolnienie rezerwacji

CREATE OR REPLACE PROCEDURE zwolnij_dlugo_oczekujace_rezerwacje()

AS $$

BEGIN

UPDATE strona_rental

SET status_id = 5

WHERE status_id = 1

AND created_at < NOW() - INTERVAL '5 minutes';



RAISE NOTICE 'Zwolniono przeterminowane rezerwacje.';

END;

$$ LANGUAGE plpgsql;
        """)
    ]
