# Generated by Django 5.2.13 on 2026-04-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0013_finalna_logika2_sql'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION fn_sprawdz_numer_prawojazdy()
RETURNS TRIGGER AS $$
BEGIN
    -- Sprawdzamy czy license_number jest NULL LUB czy jest pustym tekstem
    IF (SELECT license_number FROM strona_userprofile WHERE id = NEW.user_id) IS NULL 
       OR (SELECT license_number FROM strona_userprofile WHERE id = NEW.user_id) = '' THEN
        RAISE EXCEPTION 'Musisz dodać numer swojego prawa jazdy przed wypożyczeniem auta';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_sprawdz_prawojazdy
BEFORE INSERT ON strona_rental
FOR EACH ROW
EXECUTE FUNCTION fn_sprawdz_numer_prawojazdy();
        """)
    ]
