# Generated by Django 5.2.13 on 2026-04-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_finalna_poprawa_sql'),
    ]

    operations = [
        # 1. FUNKCJA OBLICZAJĄCA CENĘ
        migrations.RunSQL("""
                CREATE OR REPLACE FUNCTION oblicz_cene_wypozyczenia(
                    f_id_car INT, 
                    f_id_addon INT, 
                    f_days INT,
                    f_user_id INT
                )
                RETURNS DECIMAL AS $$
                DECLARE
                    v_cena_auta DECIMAL := 0;
                    v_cena_dodatku DECIMAL := 0;
                    v_wynik DECIMAL := 0;
                    v_wynik_po_rabacie DECIMAL := 0;
                    v_rabat INT := 0;
                BEGIN
                    SELECT COALESCE(price_per_day * f_days, 0) INTO v_cena_auta
                    FROM strona_car
                    WHERE id = f_id_car;

                    IF f_id_addon IS NOT NULL THEN
                        SELECT COALESCE(daily_price * f_days, 0) INTO v_cena_dodatku
                        FROM strona_addon
                        WHERE id = f_id_addon;
                    ELSE
                        v_cena_dodatku := 0;
                    END IF;

                    v_wynik := v_cena_auta + v_cena_dodatku;
                    v_rabat := COALESCE(znizka_lojalnosciowa(f_user_id), 0);
                    v_wynik_po_rabacie := v_wynik * ((100.0 - v_rabat) / 100.0);

                    IF v_wynik_po_rabacie < 0 THEN RETURN 0; END IF;

                    RETURN v_wynik_po_rabacie;
                END;
                $$ LANGUAGE plpgsql;
            """),

        # 2. FUNKCJA TRIGGERA (PRAWO JAZDY)
        migrations.RunSQL("""
                CREATE OR REPLACE FUNCTION fn_sprawdz_numer_prawojazdy()
                RETURNS TRIGGER AS $$
                DECLARE
                    found_license_number VARCHAR;
                BEGIN
                    SELECT license_number INTO found_license_number 
                    FROM strona_userprofile 
                    WHERE id = NEW.user_id;

                    IF found_license_number IS NULL OR trim(found_license_number) = '' THEN
                        RAISE EXCEPTION 'Musisz dodać numer swojego prawa jazdy przed wypożyczeniem auta';
                    END IF;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                
                CREATE OR REPLACE TRIGGER trg_sprawdz_prawojazdy
            BEFORE INSERT ON strona_rental
            FOR EACH ROW
            EXECUTE FUNCTION fn_sprawdz_numer_prawojazdy();
            """)]