# Generated by Django 5.2.13 on 2026-04-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_poprawa_sql'),
    ]

    operations = [
        migrations.RunSQL("""
        
            CREATE OR REPLACE FUNCTION znizka_lojalnosciowa(f_user_id INT)
RETURNS INT AS $$
DECLARE
    v_liczba_wynajmow INT;
BEGIN
    -- LICZYMY TYLKO OPŁACONE LUB ZAKOŃCZONE WYNAJMY
    SELECT COUNT(*) INTO v_liczba_wynajmow
    FROM strona_rental
    WHERE user_id = f_user_id 
    AND status_id IN (SELECT id FROM strona_rentalstatus WHERE name IN ('Opłacona', 'Zakończona'));

    
    IF v_liczba_wynajmow >= 10 THEN RETURN 15; -- 15% zniżki
    ELSIF v_liczba_wynajmow >= 5 THEN RETURN 10; -- 10% zniżki
    ELSIF v_liczba_wynajmow >= 1 THEN RETURN 5;  -- 5% zniżki
    ELSE RETURN 0;
    END IF;
END;
$$ LANGUAGE plpgsql;
        
        """)
    ]
