# Generated by Django 5.2.13 on 2026-04-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0016_poprawa_znizek_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalstatus',
            name='name',
            field=models.CharField(choices=[('Oczekująca', 'Oczekująca'), ('Opłacona', 'Opłacona'), ('W trakcie', 'W trakcie'), ('Zwrócona', 'Zwrócona'), ('Anulowana', 'Anulowana')], max_length=20),
        ),
    ]
