# Generated by Django 5.2.13 on 2026-04-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0017_alter_rentalstatus_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- 1. Usuwamy stary trigger, jeśli istnieje, żeby nie było błędu DuplicateObject
                DROP TRIGGER IF EXISTS trg_zmiana_oddzialu ON strona_transfer;

                -- 2. Tworzymy/Aktualizujemy funkcję
                CREATE OR REPLACE FUNCTION fcn_zmien_oddzial()
                RETURNS TRIGGER AS $$
                BEGIN
                    UPDATE strona_car
                    SET 
                        current_branch_id = NEW.to_branch_id,
                        is_available = TRUE
                    WHERE id = NEW.car_id;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                -- 3. Tworzymy trigger na nowo
                CREATE TRIGGER trg_zmiana_oddzialu
                AFTER INSERT ON strona_transfer
                FOR EACH ROW
                EXECUTE FUNCTION fcn_zmien_oddzial();
                """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_zmiana_oddzialu ON strona_transfer;
                DROP FUNCTION IF EXISTS fcn_zmien_oddzial();
                """
        ),
    ]