# Generated by Django 5.2.13 on 2026-04-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0018_dodanie_trigera_sql'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION public.fn_zarzadzaj_dostepnoscia() 
RETURNS trigger LANGUAGE plpgsql AS $function$ 
BEGIN 
    -- SCENARIUSZ 1: Jeśli rezerwacja zostaje ANULOWANA (5) lub AUTO WRACA (9)
    IF (TG_OP = 'UPDATE') THEN
        IF NEW.status_id IN (5, 9) THEN 
            UPDATE strona_car SET is_available = TRUE WHERE id = NEW.car_id; 
        END IF;
        RETURN NEW;

    -- SCENARIUSZ 2: Jeśli całkowicie USUWAAMY rekord z bazy
    ELSIF (TG_OP = 'DELETE') THEN 
        UPDATE strona_car SET is_available = TRUE WHERE id = OLD.car_id; 
        RETURN OLD; 
    END IF;

    RETURN NEW; 
END; $function$
        """)
    ]
