# Generated by Django 5.2.13 on 2026-04-14 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0019_poprawa_trigera_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numer prawa jazdy musi mieć 9 cyfr (np. 123456789) lub format 12345/67/89.', regex='^[0-9]{5}/[0-9]{2}/[0-9]{2}$|^[0-9]{9}$')]),
        ),
    ]
