# Generated by Django 5.2.13 on 2026-04-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0020_alter_userprofile_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_id',
        ),
    ]
