# Generated by Django 5.2.13 on 2026-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0021_remove_invoice_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('Blik', 'Blik'), ('Karta', 'Karta'), ('Przelew', 'Przelew')], max_length=20),
        ),
    ]
