# Generated by Django 5.2.13 on 2026-04-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0022_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION fn_generuj_fakture()
RETURNS TRIGGER AS $$
DECLARE
    v_inv_number TEXT;
BEGIN
	IF (NEW.status_id = 6 AND (OLD.status_id IS NULL OR OLD.status_id != 6)) THEN
		-- To generuje numer: FV / ID rezerwacji / ROK
    	v_inv_number := 'FV/' || NEW.id || '/' || TO_CHAR(NOW(), 'YYYY');
		INSERT INTO strona_invoice(invoice_number,issued_at,rental_id) 
		VALUES (v_inv_number,NOW(),NEW.id);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_generuj_fakture
AFTER UPDATE ON strona_rental
FOR EACH ROW
EXECUTE FUNCTION fn_generuj_fakture();

CREATE OR REPLACE FUNCTION fn_zapisz_platnosc()
RETURNS TRIGGER AS $$
DECLARE 
	v_method_id INTEGER;
BEGIN
	SELECT id INTO v_method_id FROM strona_paymentmethod WHERE name = 'Przelew' LIMIT 1;
	IF (NEW.status_id = 6 AND (OLD.status_id IS NULL OR OLD.status_id != 6)) THEN
		INSERT INTO strona_payment(amount,timestamp,method_id,rental_id,user_id)
		VALUES(NEW.total_price,NOW(),v_method_id,NEW.id,new.user_id);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_generuj_platnosc
AFTER UPDATE ON strona_rental
FOR EACH ROW
EXECUTE FUNCTION fn_zapisz_platnosc();
        """)
    ]
