# Generated by Django 5.2.13 on 2026-04-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0023_dodanie_trigerow_sql'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='phone_number',
            new_name='work_phone_number',
        ),
    ]
