# Generated by Django 5.2.13 on 2026-04-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0023_dodanie_trigerow_sql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_id_number',
        ),
    ]
