# Generated by Django 5.2.13 on 2026-04-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0024_remove_employeeprofile_employee_id_number'),
        ('strona', '0024_rename_phone_number_employeeprofile_work_phone_number'),
    ]

    operations = [
    ]
