# Generated by Django 5.2.13 on 2026-04-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0025_merge_20260420_1717'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- 1. Blokada wieku (musi być co najmniej 18 lat wstecz od dziś)
                ALTER TABLE strona_userprofile 
                ADD CONSTRAINT check_wiek_18 
                CHECK (birth_date <= CURRENT_DATE - INTERVAL '18 years');

                -- 2. Prosta walidacja numeru telefonu (musi mieć min. 9 znaków)
                ALTER TABLE strona_userprofile 
                ADD CONSTRAINT check_phone_length 
                CHECK (length(phone_number) >= 9);
                """,
            reverse_sql="""
                ALTER TABLE strona_userprofile DROP CONSTRAINT IF EXISTS check_wiek_18;
                ALTER TABLE strona_userprofile DROP CONSTRAINT IF EXISTS check_phone_length;
                """
        ),
    ]