# Generated by Django 6.0.3 on 2026-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0026_auto_20260420_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
