# Generated by Django 6.0.3 on 2026-04-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0027_userprofile_license_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='license_image',
        ),
    ]
