# Generated by Django 6.0.3 on 2026-04-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0028_remove_userprofile_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Opłacona'), ('PENDING', 'Oczekująca'), ('CANCELLED', 'Anulowana')], default='PAID', max_length=20),
        ),
    ]
