# Generated by Django 5.2.13 on 2026-04-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0029_invoice_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION public.fn_generuj_fakture()
                 RETURNS trigger
                 LANGUAGE plpgsql
                AS $function$
                DECLARE
                    v_inv_number TEXT;
                BEGIN
                    IF (NEW.status_id = 6 AND (OLD.status_id IS NULL OR OLD.status_id != 6)) THEN
                        v_inv_number := 'FV/' || NEW.id || '/' || TO_CHAR(NOW(), 'YYYY');

                        INSERT INTO strona_invoice(invoice_number, issued_at, rental_id, status) 
                        VALUES (v_inv_number, NOW(), NEW.id, 'PAID'); 
                    END IF;
                    RETURN NEW;
                END;
                $function$;
                """,
            reverse_sql=""
        ),  # <--- PRZECINEK TUTAJ TEŻ JEST WAŻNY
    ]
