# Generated by Django 5.2.13 on 2026-04-25 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0030_update_invoice_trigger_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(help_text="Wpisz numer bez spacji i znaku '+' z początkiem kierunkowym", max_length=15, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi składać się wyłącznie z cyfr (od 9 do 15).', regex='^\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='RentalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('PICKUP', 'Wydanie (Stan Przed)'), ('RETURN', 'Zwrot (Stan Po)')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.PositiveIntegerField(verbose_name='Przebieg')),
                ('fuel_level', models.PositiveIntegerField(default=100, verbose_name='Poziom paliwa %')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Uwagi / Uszkodzenia')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='strona.rental')),
            ],
            options={
                'unique_together': {('rental', 'inspection_type')},
            },
        ),
    ]
