# Generated by Django 6.0.3 on 2026-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0031_alter_userprofile_phone_number_rentalinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinspection',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Przebieg'),
        ),
    ]
